M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-09-13T17:28:16+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T17:28:16+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X71.25Y-77.575
X78.75Y-77.575
M30
